name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: {node-version: '18'}
      
      # 1. Java 17 set karo aur path lock karo
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clean & Build
        run: |
          # 2. Path force karo
          export JAVA_HOME=$JAVA_HOME_17_X64
          export PATH=$JAVA_HOME/bin:$PATH
          
          rm -rf android/
          npm install --legacy-peer-deps
          npx cap add android
          npx cap sync android
          
          # 3. Yandex SDK direct (No Plugin)
          echo "dependencies { implementation 'com.yandex.android:mobileads:7.5.0' }" >> android/app/build.gradle
          
          cd android
          chmod +x ./gradlew
          # Clean build without cache
          ./gradlew clean assembleRelease

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: EarnX-Final-Build
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
